[package]
name = "mark_and_compact"
version = "0.1.0"
edition = "2021"

[features]
default = ["log/max_level_debug", "log/release_max_level_info", "gc_api/slab"]

[dependencies]
gc_api = { path = "../.." }
log = "0.4.17"

[dev-dependencies]
gc_benchmark_utils = { path = "../gc_benchmark_utils" }
